### PR TITLE
Alps release m0.mp21 linaro

### PR DESCRIPTION
**Pull request by n005056**
Modify by Archermind to Implement some new features.

### CODE REVIEW

**Comment by iamblue** [comment]
hello , when i type `make mrproper` , it show `./scripts/Makefile.clean:17: drivers/misc/mediatek/base/power/mt2701_dcm/Makefile: No such file or directory`.

BTW, I can't find the mt2701_dcm folder in this repo.

**Comment by n005056** [comment]
Hi iamblue, the linux kernel can't build alone, it should merge into AOSP and build with android tool-chain, then you can build kernel to vmlinux or bootimage.

**Comment by n005056** [comment]
We will have a test about your issue, if any update, we will let you know form github.

Thanks for your attention to X20 Board.

**Comment by berolinaro** [comment]
The patch works perfectly for me. The "make mrproper" problem is unrelated to the patch, and is caused by references to mt2701_dcm/ in drivers/misc/mediatek/base/power/Makefile (in the original tree). Will send a separate pull request to fix that one.

**Comment by berolinaro** [comment]
Issue from @iamblue 's comment is fixed by pull request #4 
https://github.com/helio-x20/linux/pull/4

**Pull request merged**
